name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🧲
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v2
        with:
        version: 6.0.2

      - name: Install and Build 🏗️
        run: |
          pnpm install
          pnpm run build

      - name: Run Linters 🌀
        run: pnpm run lint

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
